### PR TITLE
Reject unsafe characters in `.aleo` file parser.

### PR DESCRIPTION
**Pull request by acoglio**
Rejects (1) all control ASCII characters except HT and LF and CR, and (2)
Unicode bidi characters, in both comments and string literals. These syntactic
entities (comments and string literals) should be the only part of Aleo
instructions that could otherwise allow these characters.

Prior to this commit, bidi characters were rejected from string literals, but
not from comments. And all ASCII characters were accepted.

Added tests to demonstrate rejection.

Also added some positive tests for string literals, which were not present in
the file for parsing string literals.

This addresses #1039, for `.aleo` files.

### CODE REVIEW

**Comment by howardwu** [comment]
This looks great @acoglio. Where are you planning to plug this sanitize checker in?

My guess is we could benefit from it in the parser of `Identifier` and `String`, which will then propagate to everything upstream (such as `ProgramID`, `Locator`, etc.)

**Comment by acoglio** [comment]
@howardwu I think that it should be already integrated into the parsing of `.aleo` files, but I may be wrong because I'm not familiar with the rest of the snarkVM code yet. The new `Sanitize::parse_safe_char` function is called (indirectly) by `Sanitizer::parse`, i.e. any time we parse comments and whitespace, so it should apply to all comments. For string literals, given that there was already an `UNSUPPORTED_CODE_POINTS` list, I added the forbidden ASCII codes to it as an initial step, but I think we should rework that code to call `Sanitizer::parse_safe_char` too (so it's a single point of validation), as noted in the comment there. identifiers should not need this because we are already using `nom`'s parsers for ASCII letters and digits and underscore, so anything outside that narrow range would just not parse as part of an identifier.

**Comment by howardwu** [comment]
Rebased here

**Comment by howardwu** [comment]
Rebased again for clippy.

**Review by howardwu — APPROVED** [review]
LGTM

**Pull request merged**
