### PR TITLE
[Perf] Reduce allocations in ToBits for Plaintext

### PR DESCRIPTION
**Pull request by ljedrz**
A revival of https://github.com/AleoNet/snarkVM/pull/2458, as requested by @vicsn.

### CODE REVIEW

**Review by raychu86 — DISMISSED** [review]
LGTM. This PR was already approved and merged, prior to revert.

**Comment by ljedrz** [comment]
[CI run link](https://app.circleci.com/pipelines/github/ProvableHQ/snarkVM?branch=perf%2Fplaintext_bits_allocs-ci)

**Review by raychu86 — APPROVED** [review]
LGTM

**Review by zosorock — APPROVED** [review]
lgtm as well

**Pull request merged**
