### PR TITLE
Decouples DPC from Ledger

### PR DESCRIPTION
**Pull request by howardwu**
## Motivation

Implements #272:

- Removes `LedgerScheme` from `DPCScheme`
- Removes `contains_memo` from `LedgerScheme`, we no longer enforce uniqueness on transaction memos
- #276 
- Renames current `Components` to `Parameters`
- Renames current `NoopProgramSNARK` to `ProgramSNARK` (now that the circuit is decoupled)

## Notes

This PR resamples parameters.

### CODE REVIEW

**Comment by howardwu** [comment]
^This commit demonstrates equivalence of the DPC circuits to the sampled parameters since PR #276 (17 commits ago).

**Comment by howardwu** [comment]
Given the immensity of refactors in the PR, I will attempt to preserve the existing sampled parameters until the very end to demonstrate equivalence.

**Review by weikengchen — APPROVED** [review]
Went through all the files (actually, a lot of the changes come from #278). And I think it is ready.

**Review by raychu86 — APPROVED** [review]
Quite a number of nice structural changes. LGTM.

**Comment by howardwu** [comment]
Thanks for reviewing! Given some other improvements I intend to make that will require resampling parameters, I will go ahead and merge this one in as is

**Pull request merged**
