### PR TITLE
Speed up Program tests

### PR DESCRIPTION
**Pull request by ljedrz**
This PR is an attempt to greatly speed up the tests related to https://github.com/AleoHQ/snarkVM/issues/985 by introducing a test-only cached version of `Process::load`.

### CODE REVIEW

**Comment by ljedrz** [comment]
```
Checking 'assert.eq' for '"iqYQsylDNTums8Skpf0UBPzgnUm2H9twnHEsCT16H2m9zTFJW".public' and '"zBVj86m1ZJBFgHruUBQDLPRmYzMAm".public'
thread 'program::instruction::operation::assert::tests::test_assert_eq_succeeds' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`: Constant constraint failed: (0 * 1) =?= 1', /home/circleci/project/circuit/environment/src/circuit.rs:156:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    program::instruction::operation::assert::tests::test_assert_eq_succeeds
```
Cc https://github.com/AleoHQ/snarkVM/issues/986

**Comment by ljedrz** [comment]
This PR roughly halves the amount of time taken by the `compiler` job (from more than 1h to under 30m). I'll try to find other speedups, but this one seems to be significant enough on its own.

**Comment by ljedrz** [comment]
The strategic addition of 2 `Arc`s further improved the performance of the slowest `compiler` tests: 
- `test_is_eq_fails`
- `test_is_neq_fails`
- `test_assert_eq_fails`
- `test_assert_eq_fails`

by ~98%.

The duration of the `compiler` job is now ~25m.

**Comment by ljedrz** [comment]
It might also be a good idea to bump the number of cores dedicated to the `compiler` job, as locally (I have 24 logical cores) it executes in 13 minutes (with these changes + https://github.com/AleoHQ/snarkVM/pull/1013), which would make it about as fast as the `parameters` job.

**Review by howardwu — APPROVED** [review]

**Pull request merged**
