### PR TITLE
fix construct transaction path in inclusion

### PR DESCRIPTION
**Pull request by peinlcy**
append transaction leaf to transaction tree before prove its existance

### CODE REVIEW

**Comment by howardwu** [comment]
Closing as this would introduce a vulnerability. One cannot use their own leaf to prove `local` path. The local path must exist beforehand.

**Comment by howardwu** [comment]
Just noticed the report. Will review and follow up there.

**Comment by peinlcy** [comment]
> Closing as this would introduce a vulnerability. One cannot use their own leaf to prove `local` path. The local path must exist beforehand.

Sorry i still have a question, if the transition with local input task is not appended to the transaction tree, how it can calculate the transaction path, won't it be an out-of-index error ?  (line 53 in inclusion/execute.rs)

**Comment by peinlcy** [comment]
I write a simple test

**Comment by peinlcy** [comment]
I add a unittest to cover the scene of local record, can u review it plz
https://github.com/AleoHQ/snarkVM/pull/1624

**Pull request closed without merging**
