### PR TITLE
Fix seg fault in existing cuda implementation

### PR DESCRIPTION
**Pull request by kernel32uiuc**
## Motivation
The cuda implementation causes a segmentation fault due to the JIT compilation of Cuda kernel and rust compiler optimizations. If we want to use the JIT for cuda kernels, opt-level:0 fixes the segmentation fault, but it hurts the performance badly. Instead, we can just get rid of the JIT and load the kernel directly. 

## Test Plan
`cargo test test_msm_cuda --features cuda -- --nocapture 
`
this was failing with a segfault; after the changes, the test passes and I see the following output:

> running 1 test
> Using 'NVIDIA GeForce .......' as CUDA device with compute capability 7.5
> test msm::variable_base::tests::test_msm_cuda ... ok
> 
> test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 80 filtered out; finished in 43.59s
>

### CODE REVIEW

**Comment by kernel32uiuc** [comment]
@Protryon, I have spent hours fixing the segfault in the msm cuda implementation. I figured out the root cause last week, but did not help me mining a block. After I see the community update yesterday, I decided to send the PR. JIT compilation seems to be problematic with the rust compiler optimizations. I dig into it deeper, but could not come up with a fix, so I got rid of the JIT.

**Comment by xbeastx** [comment]
Did you try transactions tests?
```
$ cd dpc && cargo bench --bench transaction --features "print-trace,snarkvm-algorithms/cuda"
...
Start:   {Groth 2016}::Prove
··Start:   Prover
····Start:   Constraint synthesis
······Start:   BoweHopwoodPedersenCRH::Setup: 16 segments of 32 3-bit chunks; {0,1}^{1536} -> G
······End:     BoweHopwoodPedersenCRH::Setup: 16 segments of 32 3-bit chunks; {0,1}^{1536} -> G 1.305ms
······Start:   BoweHopwoodPedersenCRH::Setup: 16 segments of 32 3-bit chunks; {0,1}^{1536} -> G
······End:     BoweHopwoodPedersenCRH::Setup: 16 segments of 32 3-bit chunks; {0,1}^{1536} -> G 1.213ms
····End:     Constraint synthesis ..................................................1.523s
····Start:   R1CS to QAP witness map
····End:     R1CS to QAP witness map ...............................................399.401ms
····Start:   Compute A
····End:     Compute A .............................................................446.989ms
····Start:   Compute B in G1
····End:     Compute B in G1 .......................................................361.922ms
····Start:   Compute B in G2
····End:     Compute B in G2 .......................................................835.96ms
····Start:   Compute C
····End:     Compute C .............................................................833.724ms
··End:     Prover ..................................................................4.404s
End:     {Groth 2016}::Prove .......................................................4.460s
Start:   {Groth 2016}::Verify
··Start:   Convert input to E::Fr
··End:     Convert input to E::Fr ..................................................2.705µs
··Start:   Verify proof w/ input len: 6
··End:     Verify proof w/ input len: 6 ............................................2.514ms
End:     {Groth 2016}::Verify ......................................................2.544ms
thread 'main' panicked at 'assertion failed: N::InnerSNARK::verify(N::inner_verifying_key(), &inner_public, &inner_proof)?', /root/test_gpu/snarkVM/dpc/src/virtual_machine/virtual_machine.rs:106:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by xbeastx** [comment]
Probably you was fixed this issue: https://github.com/Protryon/cuda-oxide/pull/1

**Comment by kernel32uiuc** [comment]
@howardwu could you please review this PR?

**Pull request closed without merging**
