### PR TITLE
[Chore] Use type_name instead of literals for LiteralType::parse

### PR DESCRIPTION
**Pull request by ljedrz**
A revival of https://github.com/AleoNet/snarkVM/pull/2459, as requested by @vicsn.

### CODE REVIEW

**Review by raychu86 — APPROVED** [review]
LGTM. This change was already approved and merged previously, prior to revert.

**Comment by ljedrz** [comment]
[CI run link](https://app.circleci.com/pipelines/github/ProvableHQ/snarkVM?branch=refactor%2Ffutureproof_literals-ci)

**Review by vicsn — APPROVED** [review]

**Comment by ljedrz** [comment]
Rebased for a cleaner merge experience.

**Review by zkxuerb — APPROVED** [review]
LGTM

**Pull request merged**
