### PR TITLE
Deduplicate macro code in parameters

### PR DESCRIPTION
**Pull request by ljedrz**
While looking at the issue of parameters not downloading, I noticed that plenty of code is duplicated in the related macros, making it harder to analyze; it will also cause trouble if in the future something needs to be adjusted there and the dev doesn't know or forgets that there are two spots where the change needs to be made.

### CODE REVIEW

**Comment by ljedrz** [comment]
Cc @julesdesmit, as I see your comments in this code.

**Review by jules — APPROVED** [review]
Good catch - LGTM, fine to merge IMO if CI is all green :)

**Comment by ljedrz** [comment]
Cc https://github.com/AleoHQ/snarkVM/pull/1092 for the failed `clippy` job

**Comment by ljedrz** [comment]
The parameters-related CI job failures seem to be unrelated, but it would be best to merge this change only once they can be downloaded again.

**Comment by ljedrz** [comment]
Rebased.

**Review by howardwu — APPROVED** [review]
LGTM

**Pull request merged**
