### PR TITLE
[Perf] Use heuristics to avoid allocations in Sanitizer::str_till_eol

### PR DESCRIPTION
**Pull request by ljedrz**
(transferred from https://github.com/ProvableHQ/snarkVM/pull/6, and asking @d0cd for a review as suggested there)

The `Sanitizer` is used very prominently in our parsing functions, and it is also a source of many allocations, most of which are temporary and avoidable.

The potential perf improvements are quite large, and I've measured them both with a 15-minute run of a `--dev` node and using `hyperfine` on a small binary that parsed all the valid `.aleo` programs currently present in the snarkVM codebase.

dev node:
- all allocs are down ~**15%**, of which almost all are temporary
- in `Program::from_str` specifically, allocs are reduced by ~**64%**, of which temp allocs ~**88%**

parsing all `.aleo` programs using `Program::from_str`:
- allocs are reduced by ~**41%**
- growth reallocs are down ~**70%**
- runtime is reduced by ~**31%**

### CODE REVIEW

**Comment by ljedrz** [comment]
[CI run link](https://app.circleci.com/pipelines/github/ProvableHQ/snarkVM?branch=perf%2Fparsing_sanitizer2-ci)

**Comment by raychu86** [comment]
@ljedrz Could you fix the `cargo fmt` issue and rerun CI?

**Comment by ljedrz** [comment]
The `fmt` issue doesn't come from this PR, but seems to be caused by the new `nightly` compiler, meaning it would happen in all the other PRs as well. While I recommend it to be handled in its own PR, [this](https://app.circleci.com/pipelines/github/ProvableHQ/snarkVM?branch=perf%2Fparsing_sanitizer2_ci) is a new CI branch for this one.

**Comment by vicsn** [comment]
Superseded by https://github.com/AleoNet/snarkVM/pull/2563 to merge in `aleonet/staging`

**Review by gluax — APPROVED** [review]

**Comment by ljedrz** [comment]
Superseded by https://github.com/AleoNet/snarkVM/pull/2563.

**Pull request closed without merging**
