### PR TITLE
feat: test targets

### PR DESCRIPTION
**Pull request by joske**
## Motivation

Add feature flag to be able to lower coinbase and proof targets for testing purposes.

### CODE REVIEW

**Review by vicsn — DISMISSED** [review]
LGTM if you remove the prints

**Comment by raychu86** [comment]
Changes look reasonable. My main question is (posted in sister snarkOS PR) - https://github.com/AleoNet/snarkOS/pull/3378#issuecomment-2284576546

**Comment by raychu86** [comment]
Would we want to consider Doing these features only on `TestnetV0` and `CanaryV0`? Just for cleanliness of `MainnetV0`? I don't have strong preferences either way, but just a thought.

**Comment by vicsn** [comment]
> Would we want to consider Doing these features only on TestnetV0 and CanaryV0? Just for cleanliness of MainnetV0? I don't have strong preferences either way, but just a thought.

I think its a great idea, to further reduce the chance this ever makes it into production mainnet.

**Comment by vicsn** [comment]
Superseded by: https://github.com/AleoNet/snarkVM/pull/2554

**Pull request closed without merging**
