### PR TITLE
Updating Mainnet Beta genesis block for release v0.1.0

### PR DESCRIPTION
**Pull request by zosorock**
## Motivation
Updating Mainnet Beta genesis block for release `v0.1.0`

## Related PRs
https://github.com/AleoNet/snarkOS/pull/3393

### CODE REVIEW

**Review by Meshiest — DISMISSED** [review]
LGTM

**Review by zkxuerb — DISMISSED** [review]
LGTM

**Comment by raychu86** [comment]
The genesis block's timestamp may optionally be updated via the `GENESIS_TIMESTAMP`. This was done for `CanaryV0` and `TestnetV0`, but not yet for `MainnetV0`.

If the change is desired, the genesis block would need to be resampled again (all other fields will be the same).

**Comment by snarkworld** [comment]
LGTM - w/ exception to timestamp

**Review by snarkworld — DISMISSED** [review]

**Review by snarkworld — DISMISSED** [review]
LGTM (pending CI)

**Review by zkxuerb — DISMISSED** [review]
LGTM!!

**Review by evanmarshall — DISMISSED** [review]

**Review by snarkworld — DISMISSED** [review]

**Review by zkxuerb — DISMISSED** [review]

**Review by raychu86 — DISMISSED** [review]

**Review by xxxecho1225 — APPROVED** [review]

**Review by evanmarshall — DISMISSED** [review]

**Review by zkxuerb — APPROVED** [review]

**Review by snarkworld — APPROVED** [review]

**Review by raychu86 — APPROVED** [review]
LGTM pending CI

**Comment by ghostant-1017** [comment]
Need to update the `MAX_COMMITTEE_SIZE` from `15` to `16`
https://github.com/AleoNet/snarkVM/blob/mainnet-staging/console/network/src/mainnet_v0.rs#L159

**Comment by raychu86** [comment]
> Need to update the `MAX_COMMITTEE_SIZE` from `15` to `16` https://github.com/AleoNet/snarkVM/blob/mainnet-staging/console/network/src/mainnet_v0.rs#L159

@ghostant-1017 This should already be done here - https://github.com/AleoNet/snarkVM/pull/2542/files#diff-020f8a47f91e2989abed49d5aeb48eb194da952cee392de676de5f75b45b1913R159. Please confirm if you see otherwise.

**Comment by ghostant-1017** [comment]
> > Need to update the `MAX_COMMITTEE_SIZE` from `15` to `16` https://github.com/AleoNet/snarkVM/blob/mainnet-staging/console/network/src/mainnet_v0.rs#L159
> 
> @ghostant-1017 This should already be done here - https://github.com/AleoNet/snarkVM/pull/2542/files#diff-020f8a47f91e2989abed49d5aeb48eb194da952cee392de676de5f75b45b1913R159. Please confirm if you see otherwise.

Sorry, I ignored it.

**Comment by ghostant-1017** [comment]
Why do we need to set this value to 16? If a new validator bonds, there will be problems, right?  There will be 800,000 ACs minted per day, after tens of days, there will be enough ACs to bond as a validator.

**Comment by raychu86** [comment]
> Why do we need to set this value to 16? If a new validator bonds, there will be problems, right?

There is now 16 validators in the genesis committee set. The implications are the same as before when there was 15, except now the genesis has one additional.

**Comment by hairtail** [comment]
Wen can we get this PR approved and merged hahaha

**Comment by ghostant-1017** [comment]
> Why do we need to set this value to 16? If a new validator bonds, there will be problems, right? There will be 800,000 ACs minted per day, after tens of days, there will be enough ACs to bond as a validator.

Yes, I mean if we have more than 16 validators after ten days of mainnet launch .

**Comment by raychu86** [comment]
All `bond_public` calls for new validators past the 16 will be safely aborted. This maximum value will need to be updated before new validators can safely join.

**Comment by ghostant-1017** [comment]
> All `bond_public` calls for new validators past the 16 will be safely aborted. This maximum value will need to be updated before new validators can safely join.

Thank you Raymond! I see the logic.

**Pull request merged**
