### PR TITLE
[tests] Add a few tests for parsing `call`.

### PR DESCRIPTION
**Pull request by acoglio**
These actually demonstrate a probably undesired behavior in the current parser, namely allowing a "dangling" `into` with no destination registers.

### CODE REVIEW

**Review by bendyarm — APPROVED** [review]
This PR is good since the tests document the current behavior,

**Comment by d0cd** [comment]
This PR also contains the fix for the dangling `into`.

**Comment by acoglio** [comment]
@d0cd I can't 'approve' this PR because I'm the one who originally opened it, but your fix to the parser looks good.

**Comment by howardwu** [comment]
I'll go ahead and approve and merge this, given the useful parsing fix.

**Review by howardwu — APPROVED** [review]
LGTM

**Pull request merged**
