### PR TITLE
[Fix] Disable `benches/instruction.rs`

### PR DESCRIPTION
**Pull request by d0cd**
This PR disables `benches/instruction.rs` because it significantly increases build/clippy times.

### CODE REVIEW

**Comment by howardwu** [comment]
Does the bench file need to be commented out?

**Comment by d0cd** [comment]
Yes, otherwise clippy still processes the code.

**Comment by howardwu** [comment]
Can you add a comment to the file then?

**Comment by howardwu** [comment]
Never mind. I really need this in, merging.

**Pull request merged**
