### PR TITLE
Signature scheme cleanup and add flexibility to signature verification gadget

### PR DESCRIPTION
**Pull request by raychu86**
## Motivation

This PR removes unnecessary trait requirements like `digest` from Schnorr parameters and Schnorr verification gadgets. 

Additionally, more support has been added to the Signature verification gadget in order to support the signature scheme used in the Account model (GroupEncryption), which is a wrapper around the Schnorr signature implementation.

### CODE REVIEW

**Comment by weikengchen** [comment]
I have a PR that very likely will conflict entirely with this PR. So I will manually merge this PR's content into my PR. On the way!

**Comment by weikengchen** [comment]
So everything in this PR has been manually merged into #246, as well as adding Poseidon for the version from group encryption.

**Comment by howardwu** [comment]
Whats the status on this PR?

**Comment by weikengchen** [comment]
I think at this moment it is either to merge #246 or finalize this PR, merge it first, and then fix the conflicts in #246.

Pratyush and I have settled down to use Poseidon parameters optimized for the constraint world for now, so I can move forward #246 correspondingly. I think there is no more to add in #246.

**Comment by raychu86** [comment]
I think since #246 is ready to go and it seems to already have the updates from this PR, we can change the base and merge it into #246. @weikengchen thoughts?

**Comment by weikengchen** [comment]
#246 has already manually merged the changes in this PR up to the latest commit. That is, if #246 is merged, this can be closed.

**Comment by raychu86** [comment]
Let's do that and close this PR when #246 is merged

**Comment by howardwu** [comment]
Closing this PR as it has already been merged in with PR #246

**Pull request closed without merging**
