### PR TITLE
[Feature] Update targets

### PR DESCRIPTION
**Pull request by d0cd**
**This PR should be merged AFTER https://github.com/AleoNet/snarkVM/pull/2502**
**This PR was originally made and approved [here](https://github.com/ProvableHQ/snarkVM/pull/20)**

This PR updates the GENESIS_COINBASE_TARGET and GENESIS_PROOF_TARGET to empirically calibrated values.

@zosorock
The order of operations for this PR is:

- [x] After https://github.com/AleoNet/snarkVM/pull/2502 is merged in, the PR target should be updated to AleoNet/snarkvm/mainnet-staging.
- [x] The genesis blocks for mainnet, testnet-beta, and canary must all be resampled and uploaded to the feat/update-target branch.
- [x] Resample test expectations.
- [x] Run the CI by merging feat/update-target into feat/update-target-ci. The CI run is [here](https://app.circleci.com/pipelines/github/ProvableHQ/snarkVM/150/workflows/f08f1f1b-5af5-4360-a5e4-48e51bc6cf75)
- [x] Once CI passes, merge the PR.

Please ping @d0cd, for any logistics regarding the above steps.

### CODE REVIEW

**Review by vicsn — DISMISSED** [review]

**Review by evanmarshall — COMMENTED** [review]
We'll need to update this comment: https://github.com/AleoNet/snarkVM/pull/2503/files#diff-0accda075535a9bb27fbe2d62888746cc34c05a78a3652a89225eec8614743cdR1059 b/c now we want to support bonding to delegators not in the committee as part of the genesis block.

Additionally, there should now be checks of the `delegated` mapping namely: check that each bonded_balance per validator sums to the amount in the `delegated` mapping.

**Review by raychu86 — APPROVED** [review]
LGTM assuming CI passes.

A small change was made to support delegation to to non-committee validator addresses in the genesis block. Despite how innocent this change is, it would be preferred to have additional unit testing (and not just integration testing) to to fully guarantee correctness.

**Comment by Meshiest** [comment]
Can you provide the genesis block JSONs again?

**Review by apruden2008 — APPROVED** [review]
Based on reviews and comments above, merging this in. 

Regarding the nits and fixes (and proposed additional unit tests), I support adding those in the future but for now I think the case that these are addressing is an edge case not the main case.

**Comment by ghostant-1017** [comment]
Hi @d0cd ,have you evaluated how much CPU is needed to calculate this `PROOF_TARGET`? The current value seems too high.

**Pull request merged**
