### PR TITLE
Implement CRH and CRHGadget for Poseidon

### PR DESCRIPTION
**Pull request by raychu86**
## Motivation

This PR implements the `CRH` trait for `PoseidonCryptoHash` and the `CRHGadget` trait for `PoseidonCryptoHashGadget`.  This is needed to enable Merkle trees to use the Poseidon hash function.

One thing that should be updated is the CRH attribute, `INPUT_SIZE_BITS`, which is currently hard-coded for the Poseidon impl.

## Test Plan

Tests have been added to check that Poseidon usage in Merkle Trees is valid.

### CODE REVIEW

**Comment by howardwu** [comment]
`INPUT_SIZE_BITS` can be a const generic, but given our priorities I think this is fine for now

**Review by weikengchen — APPROVED** [review]
The code looks good. 

One thing to double-check: although we have implemented the FromBytes and ToBytes for PoseidonParameters, they are not going to be used anywhere right? Since that would increase unnecessary overhead.

**Comment by weikengchen** [comment]
It would be preferred to make the FromBytes and ToBytes of PoseidonParameters as dummies, as we expect the parameters to come directly from the field.

**Comment by weikengchen** [comment]
We may in the future extend the syntax of CRH. The current CRH syntax still forces the intermediate CRH values to be converted into bytes and then converted back.

It is slightly challenging, as Poseidon CRH is very different from existing CRHs, and our Merkle tree design is specialized for existing CRHs.

**Comment by howardwu** [comment]
Agreed on all of the points you're making Weikeng. I'll open a Github issue to track this discussion.

In the meantime Ray, let's proceed and make sure to resolve this before `testnet2` goes to prod.

**Review by howardwu — APPROVED** [review]

**Comment by howardwu** [comment]
#264

**Comment by raychu86** [comment]
Following up on your question Weikeng, the ToBytes and FromBytes impls for the PoseidonParameters aren't actually being used anywhere.

It took me maybe a few minutes to write the serializations as it was quite trivial, but agreed that we may want to just make them dummies.

**Pull request merged**
