### PR TITLE
Implements BHP commitments, switches all Pedersen commitments to BHP, updates testnet1 program SNARK to Groth16 and ID CRHs to Poseidon

### PR DESCRIPTION
**Pull request by howardwu**
## Motivation

- Implements BHP commitments
- Switches all Pedersen commitment usage in DPC `Parameters` to BHP commitments
- Updates `testnet1` program SNARK to Groth16, inner and program ID CRHs to Poseidon

## Test Plan

- Adds commitment parameter serialization tests for BHP native
- Adds native and gadget equivalence tests for BHP commitments, BHP compressed commitments, and Pedersen compressed commitments

## Notes

This PR resamples parameters for both `testnet1` and `testnet2`

### CODE REVIEW

**Comment by howardwu** [comment]
Should we rename all Bowe Hopwood Pedersen primitives to BHP? e.g. BoweHopwoodPedersenCompressedCommitmentGadget is a *mouthful*

**Comment by weikengchen** [comment]
Just to add that changing the DPC trait impl to using `PoseidonCryptoHash` would not give the full speed boost---since by default, it would call the bit interface of Poseidon and still incurs an overhead of bit conversions. Certain changes to make them into field elements first and then `hash_field_elements` are needed. I can take a look tomorrow and probably push to this branch (or after it is merged).

**Comment by weikengchen** [comment]
> Should we rename all Bowe Hopwood Pedersen primitives to BHP? e.g. BoweHopwoodPedersenCompressedCommitmentGadget is a _mouthful_

I totally agree. Indeed, if its parameters are more easy to specify for end users, it can just be a drop-in replacement of Pedersen.

**Comment by howardwu** [comment]
> Just to add that changing the DPC trait impl to using `PoseidonCryptoHash` would not give the full speed boost---since by default, it would call the bit interface of Poseidon and still incurs an overhead of bit conversions. Certain changes to make them into field elements first and then `hash_field_elements` are needed. I can take a look tomorrow and probably push to this branch (or after it is merged).

That sounds great, I will finish up my changes in here and after completing them hand it off to you.

(I will then resample parameters after the changes are ready)

**Comment by weikengchen** [comment]
Yes, I suspect that the CI for integration testnet1 fails because the keys do not match.

**Comment by howardwu** [comment]
I will resample parameters and update constraint sizes based on these changes just so we have a baseline here.

**Review by weikengchen — APPROVED** [review]
The changes look standard and reasonable.

**Comment by Pratyush** [comment]
btw, separately, I would just drop the `Compressed` part from BHP; the specification of BHP in the Zcash spec includes the compression (i.e. projection to one coordinate) by default, because it's only defined over TE curves. I've made this change in arkworks already.

**Pull request merged**
