### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by GoodDaisy**

### CODE REVIEW

**Review by ljedrz — APPROVED** [review]
LGTM :+1:; nit: I'd squash these 2 commits into one.

**Review by iamalwaysuncomfortable — CHANGES_REQUESTED** [review]
Any submissions to SnarkVM should make a relevant change. Typo corrections should be submitted as issues or fixed as part of larger PRs

**Comment by GoodDaisy** [comment]
Thank you for your reviews. I have squashed.

**Comment by vicsn** [comment]
> Any submissions to SnarkVM should make a relevant change. Typo corrections should be submitted as issues or fixed as part of larger PRs

Agreed, with all the recent Github spam going on we should have a policy around this. Thank you for the contributions @GoodDaisy but this is creating more noise than signal, we look forward to seeing and helping land a more meaningful PR.

**Pull request closed without merging**
