### PR TITLE
Split out the compiler crate

### PR DESCRIPTION
**Pull request by ljedrz**
Many users will likely only be interested in the `snarkvm-compiler` crate, so it makes sense to isolate it.

An alternative would be to introduce a `compiler` feature for `snarkvm` (in a fashion similar to the other features that are currently there), but it results in a much larger lockfile (in an empty project using just that dependency): `2561` lines, compared to `1548` when importing an isolated `snarkvm-compiler` crate.

In addition, the `dev-dependencies` of `snarkvm-parameters` are also made more granular, making its compilation faster.

### CODE REVIEW

**Comment by ljedrz** [comment]
The CI failures are unrelated.

Cc https://github.com/AleoHQ/snarkVM/pull/1092 for the `clippy` one.

**Comment by howardwu** [comment]
@ljedrz let's wait on this PR until #1100 is merged, which introduces time-sensitive changes for snarkVM

**Comment by ljedrz** [comment]
Sounds good; it's simple enough to redo 👌

**Comment by howardwu** [comment]
Once #1100 is merged, let's move to the `testnet3.2` branch and pursue the approach in #1165.

**Comment by ljedrz** [comment]
Done in https://github.com/AleoHQ/snarkVM/pull/1201.

**Pull request closed without merging**
